### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by harikt** [anisse/hashbot#1]
What is the license of the code ?

**Comment by anisse** [comment]
@harikt What license would you like and why ?

**Comment by harikt** [comment]
Hey, 

> What license would you like 

Its your preference. There are a variety of ones to choose. MIT, BSD, GPL etc.

> and why ?

Let me quote from https://help.github.com/articles/licensing-a-repository/

> Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

**Comment by anisse** [comment]
@harikt I already have my preferences(MIT, apache, gpl…), but if you were to use the code, which license would you like ?

**Comment by harikt** [comment]
What about MIT then ;) .

**Comment by anisse** [comment]
Fixed in the last commit.
