### ISSUE TITLE
UUID support

### ISSUE THREAD

**Issue by teruteru128** [anisse/hashbot#2]
Any plans to support UUID?

**Comment by anisse** [comment]
No, no plans. What would be the use case for finding UUIDs ?

**Comment by teruteru128** [comment]
I was thinking about converting hash, key or time to uuid and posting it, but it seems like a stupid idea.

**Comment by anisse** [comment]
Maybe there's a use case for finding new uuids that are being posted, and if anyone wants to add that, I think it would be better to fork and use their own version. The design is simple enough, there are basically two main matchers, a [fast](https://github.com/anisse/hashbot/blob/806476ed62083765fb234e8c5cebf8ec50325e25/hashbot.py#L67) one, and an [accurate](https://github.com/anisse/hashbot/blob/806476ed62083765fb234e8c5cebf8ec50325e25/hashbot.py#L68-L85) one. The [entropy filter](https://github.com/anisse/hashbot/blob/806476ed62083765fb234e8c5cebf8ec50325e25/hashbot.py#L204) should be removed initially.
